export const GET_TECHNICS = "GET_TECHNICS";
export const GET_TECHNIC = "GET_TECHNIC";
export const CREATE_TECHNICS = "CREATE_TECHNICS";
export const UPDATE_TECHNICS = "UPDATE_TECHNICS";
export const DELETE_TECHNICS = "DELETE_TECHNICS";